/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        
      },
      colors: {
        'primary-text': '#404040',
        'primary-text--disable': '#7A798A',
        'primary-text--light': '#40404020',
        'primary-text--opacity-008': '#40404020',
        'primary-text--opacity-22': '#40404022',
        'primary-text--opacity-03': '#40404003',
        'primary-text--opacity-40': '#40404022',

        'primary-accent': '#EB25B7',
        'primary-accent--darker': '#B44CAF',
        'primary-accent--darker--opacity-35': '#B44CAF35',

        'thirdly-accent': '#6a67ff',

        'primary-accent--opacity-10': '#EB25B710',
        'secondary-accent': '#FEF200',
        'secondary-accent--opacity': '#FEF20010',
        'light-grey': '#D9D9D9',
        'light-grey-l': '#A9A9A9',
        'mid-grey': '#AEAEAE',
        'light-purple': '#D6D7EE',
        purple: '#5271FF',
        'table-head': '#E9E9E9',

        success: '#14AE24',
        'success--opacity-35': '#14AE2435',
        'success--opacity-10': '#14AE2410',

        error: '#D44C4C',
        'error--hover': '#A84844',
        'error--opacity-10': '#D44C4C10',
        'error--opacity-50': '#D44C4C50',
        loading: '#64B2DD',
        warning: '#F2B235',

        'table-head': '#E9E9E9',
        'table-row-odd': '#E9E9E940',
        'white-s': '#FBFBFB',
      },
      boxShadow: {
        
      },
      fontSize: {
        
      },
      borderRadius: {
       
      },
      borderWidth: {
        
      },
      gradientColorStops: {
        
      },
      animation: {},
      aspectRatio: {},
      columns: {},
      spacing: {},
      animation: {},
      aspectRatio: {},
      backdropBlur: {},
      backdropBrightness: {},
      backdropContrast: {},
      backdropGrayscale: {},
      backdropHueRotate: {},
      backdropInvert: {},
      backdropOpacity: {},
      backdropSaturate: {},
      backdropSepia: {},
      backgroundColor: {},
      backgroundImage: {},
      backgroundOpacity: {},
      backgroundPosition: {},
      backgroundSize: {},
      blur: {},
      brightness: {},
      borderColor: {},
      borderOpacity: {},
      borderSpacing: {},
      boxShadow: {},
      boxShadowColor: {},
      caretColor: {},
      accentColor: {},
      contrast: {},
      container: {},
      content: {},
      cursor: {},
      divideColor: {},
      divideOpacity: {},
      divideWidth: {},
      dropShadow: {},
      fill: {},
      grayscale: {},
      hueRotate: {},
      invert: {},
      flex: {},
      flexBasis: {},
      flexGrow: {},
      flexShrink: {},
      fontSize: {},
      fontWeight: {},
      gap: {},
      gridAutoColumns: {},
      gridAutoRows: {},
      gridColumn: {},
      gridColumnEnd: {},
      gridColumnStart: {},
      gridRow: {},
      gridRowStart: {},
      gridRowEnd: {},
      gridTemplateColumns: {},
      gridTemplateRows: {},
      height: {},
      inset: {},
      keyframes: {},
      letterSpacing: {},
      lineHeight: {},
      listStyleType: {},
      margin: {},
      maxHeight: {},
      maxWidth: {},
      minHeight: {},
      minWidth: {},
      objectPosition: {},
      opacity: {},
      order: {},
      padding: {},
      placeholderColor: {},
      placeholderOpacity: {},
      outlineColor: {},
      outlineOffset: {},
      outlineWidth: {},
      ringColor: {},
      ringOffsetColor: {},
      ringOffsetWidth: {},
      ringOpacity: {},
      ringWidth: {},
      rotate: {},
      saturate: {},
      scale: {},
      scrollMargin: {},
      scrollPadding: {},
      sepia: {},
      skew: {},
      space: {},
      stroke: {},
      strokeWidth: {},
      textColor: {},
      textDecorationColor: {},
      textDecorationThickness: {},
      textUnderlineOffset: {},
      textIndent: {},
      textOpacity: {},
      transformOrigin: {},
      transitionDelay: {},
      transitionDuration: {},
      transitionProperty: {},
      transitionTimingFunction: {},
      translate: {},
      width: {},
      willChange: {},
      zIndex: {},
    },
  },
  plugins: [],
}
